version: '3'
services:
  minio:
    image: minio/minio
    volumes:
      - ./data:/data
    environment:
      - MINIO_ACCESS_KEY=minioaccess
      - MINIO_SECRET_KEY=miniosecret
    ports:
      - "9000:9000"
    command: server /data
